### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by scfrank** [AlanLuSun/Few-shot-keypoint-detection#1]
Hi! I've just read your paper and really enjoyed it - novel/zero shot keypoint detection could be a viable way of formulating a problem that I'm thinking about just now, and I'd love to try it out. I was wondering if you'd be able to release the code any time soon? Feel free to send me a message/email (stfr <at> di.ku.dk) if you're willing to share it privately.
Thank you so much!
Stella

**Comment by AlanLuSun** [comment]
Hey Stella,

Thank you for your interest. I plan to release the code in next month and then it will be publicly available. Regarding zero-shot keypoint detection is indeed a interesting idea and I encourage you to explore it. Moreover, we can co-work if you need help.

Best regards,
Changsheng
